[package]
name = "wasm-hearts"
version = "0.1.0"
authors = ["Stephen Merity <smerity@smerity.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]

[profile.release]
lto = true
opt-level = 's'
